version: '3'

services:  
  
  app:
    build:
      context: .
    env_file:
      - ./.env.dev
    volumes:
      - .:/pygeoapi
    #command: flask run -h 0.0.0.0
    command: tail -f /dev/null
    ports:
      - 5000:5000